{{- if .Values.secret }}
{{- range .Values.secret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.deployment.namespace }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $value := .values }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if $.Values.deployment.labels }}
  labels:
    {{- range $key, $value := $.Values.deployment.labels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
stringData:
  {{- range $key, $data := .values }}
  {{ $key }}: {{ $data }}
  {{- end }}
{{- end }}
{{- end }}