configmap:
- map_type: 'no'
  name: test-rnd-configmap
  values:
    additionalProp1: string1
    additionalProp2: string2
deployment:
  container:
  - configmaps:
    - test-rnd-configmap
    container_image: nginx:latest
    container_name: nginx-test-helm
    image_pull_policy: Always
    ports:
    - port: 80
      protocol: TCP
    resource:
      limit:
        cpu: 200m
        ram: 400Mi
      request:
        cpu: 200m
        ram: 400Mi
    secrets:
    - secret-test-ns-rnd
    volume:
    - claim_name: test-pvc
      mount_path: /
      name: test-pvc
      size: 1Gi
  labels:
    additionalProp1: label1
    additionalProp2: label2
    additionalProp3: label3
  name: test-nginx
  namespace: default
  replica:
    initial_replica: 1
    max_replica: 10
    min_replica: 1
    scale_utilization_cpu: 50
    scale_utilization_ram: 50
  strategy:
    max_surge: 1
    max_unavailable: 1
    type: RollingUpdate
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
  hosts:
  - host: test-helm-rnd.alpha.beta.klovercloud.io
    paths:
    - path: /
      path_type: ImplementationSpecific
      port: 80
      service_name: service-test-nginx
  secret: wild-cert-secret
kube_version: '1.19'
namespace:
  labels:
    rnd: rakib
  name: test-ns-rnd
pvc:
  access_mode:
  - ReadWriteOnce
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: kc-saas-dev-2
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  storage_class_name: local-path
secret:
- name: secret-test-ns-rnd
  values:
    additionalProp1: test-one
    additionalProp2: test-two
